samples: "config/samples.tsv"
barcode_mismatches: 2
# barcode_csv: "path/to/custom_barcodes.csv"  # Optional: defaults to packaged barcodes

genome:
  name: hg38
  index:
    type: Bowtie2
    prefix: "reference/hg38"
  gtf: "reference/hg38.gtf"
  # fasta: "reference/hg38.fa"
  # chromosome_sizes: "reference/hg38.chrom.sizes"
  # blacklist: "reference/hg38.blacklist.bed"

cat:
  bin_size: 5000
  n_features: 50000

rna:
  n_top_genes: 2000

enable_cat: true
enable_rna: false
# enable_integration: true  # defaults to true if both enable_cat and enable_rna are true

scnado_container: "oras://ghcr.io/alsmith151/scnado:latest"
